name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: PHP PSR Coding style
      run: |
        ./vendor/bin/phpcs app/Core/App.php --standard=PSR2
        ./vendor/bin/phpcs app/Core/Controller.php --standard=PSR2
        ./vendor/bin/phpcs app/Core/Database.php --standard=PSR2
        ./vendor/bin/phpcs app/Controllers/About.php --standard=PSR2
        ./vendor/bin/phpcs app/Controllers/Home.php --standard=PSR2
        ./vendor/bin/phpcs app/Controllers/Contact.php --standard=PSR2
        ./vendor/bin/phpcs app/Models/User.php --standard=PSR2
